Repository buildo/react-components, pull requests merged in 2018-04, with the labels that each got.

#1213 #1212: Add PasswordInput component (closes #1212)
  src/Input/Input.tsx
  src/PasswordInput/Examples.md
  src/PasswordInput/PasswordInput.tsx
  src/PasswordInput/README.md
  src/PasswordInput/index.ts
  src/PasswordInput/passwordInput.scss
  src/index.ts
  styleguide/setup.ts
  test/scripts/__snapshots__/build.test.ts.snap
Labels: breaking, waiting for merge

#1215 #1214: dropdown has weird white line (closes #1214)
  src/Dropdown/dropdown.scss
Labels: bug, waiting for merge

#1217 #1216: Input border width and placeholder font weight should be overridable (closes #1216)
  src/Input/Input.tsx
  src/Input/input.scss
Labels: waiting for merge

#1219 #1218: Dropdown: multi + small breaks the layout (closes #1218)
  src/Dropdown/dropdown.scss
Labels: waiting for merge

#1221 #1220: scss double imports cause duplication and possibly broken style depending on order of imports (closes #1220)
  src/ConfirmationInput/Examples.md
  src/ConfirmationInput/README.md
  src/ConfirmationInput/confirmationInput.scss
  src/ConfirmationInput/index.ts
  src/Input/ConfirmationInput.tsx
  src/Input/Examples.md
  src/Input/PasswordInput.tsx
  src/Input/index.ts
  src/Input/input.scss
  src/PasswordInput/Examples.md
  src/PasswordInput/README.md
  src/PasswordInput/index.ts
  src/PasswordInput/passwordInput.scss
  src/index.ts
  styleguide/setup.ts
  test/scripts/__snapshots__/build.test.ts.snap
Labels: breaking, bug, waiting for merge

#1222 Improve Meter.tsx styleability (closes #1223)
  src/Meter/Examples.md
  src/Meter/Meter.tsx
  src/Meter/meter.scss
  test/components/Meter.test.tsx
  test/components/__snapshots__/Meter.test.tsx.snap
Labels: waiting for merge

#1225 Update Meter design guidelines
  src/Meter/README.md
Labels: waiting for merge

#1227 Update focusable view design guidelines
  src/FocusableView/README.md
Labels: waiting for merge

#1228 Update meter design guidelines
  src/Meter/README.md
Labels: waiting for merge

#1226 Badge guidelines
  src/Badge/README.md
Labels: in review

#1231 #1230: Dropdown: Fix ref error when testing with Enzyme (closes #1230)
  src/Dropdown/Dropdown.tsx
Labels: bug, waiting for merge

#1233 remove react-skinnable dep (closes #1232)
  package.json
  src/utils/index.ts
  typings/react-skinnable.d.ts
  yarn.lock
Labels: defect, waiting for merge

#1234 add LoadingSpinner UI guidelines
  src/LoadingSpinner/README.md
Labels: waiting for merge

#1229 NavBar design Guidelines
  src/NavBar/README.md
Labels: waiting for merge
