Repository buildo/react-components, pull requests merged in 2018-12, with the labels that each got.

#1280 #1279: build is broken with scoped type imports (closes #1279)
  package.json
  src/Modal/ModalPortal.tsx
  src/Modal/modalWithContext.tsx
  src/Popover/Popover.tsx
  src/Scroll/ScrollView.tsx
  yarn.lock
Labels: bug, waiting for merge

#1278 #1272: Checkbox (closes #1272)
  src/Checkbox/Checkbox.tsx
  src/Checkbox/Examples.md
  src/Checkbox/README.md
  src/Checkbox/checkbox.scss
  src/Checkbox/index.ts
  src/FormField/CheckboxField.tsx
  src/FormField/Examples.md
  src/FormField/index.ts
  src/index.ts
  styleguide/setup.ts
  test/scripts/__snapshots__/build.test.ts.snap
Labels: waiting for merge

#1286 #781: Implement RadioGroup (closes #781)
  src/FormField/Examples.md
  src/FormField/RadioGroupField.tsx
  src/FormField/index.ts
  src/RadioGroup/Examples.md
  src/RadioGroup/README.md
  src/RadioGroup/RadioGroup.tsx
  src/RadioGroup/index.ts
  src/RadioGroup/radioGroup.scss
  src/index.ts
  styleguide/setup.ts
  test/scripts/__snapshots__/build.test.ts.snap
Labels: in review
