Repository buildo/react-components, pull requests merged in 2018-05, with the labels that each got.

#1238 #1237: Update all string refs (closes #1237)
  src/Dropdown/Dropdown.tsx
  src/LoadingSpinner/LoadingSpinner.tsx
  src/Modal/BackgroundDimmer.tsx
  src/Overflow/Overflow.tsx
  src/Popover/Popover.tsx
  src/Scroll/ScrollView.tsx
  src/Tablo/plugins/autosize/autosizeGrid.tsx
  src/TextOverflow/TextOverflow.tsx
  src/Toggle/Toggle.tsx
  test/components/__snapshots__/LoadingSpinner.test.tsx.snap
Labels: waiting for merge

#1235 Tootlip guidelines
  src/Tooltip/Examples.md
  src/Tooltip/README.md
Labels: in review

#1236 Menu design guidelines
  src/Menu/README.md
Labels: in review

#1243 Transalting modal guidelines
  src/Modal/README.md
Labels: waiting for merge

#1244 Translating Dropdown
  src/Dropdown/README.md
Labels: waiting for merge

#1246 #1245: Tablo with autosize on renders nothing (closes #1245)
  package.json
  src/Modal/BackgroundDimmer.tsx
  src/Tablo/plugins/autosize/autosizeGrid.tsx
  test/components/__snapshots__/BackgroundDimmer.test.tsx.snap
  test/components/__snapshots__/Badge.test.tsx.snap
  test/components/__snapshots__/Meter.test.tsx.snap
  test/components/__snapshots__/MoreOrLess.test.tsx.snap
  test/components/__snapshots__/StatefulButton.test.tsx.snap
  yarn.lock
Labels: bug, waiting for merge
