Repository buildo/react-components, pull requests merged in 2018-03, with the labels that each got.

#1183 meter-ux
  src/Meter/README.md
Labels: in review

#1186 AsyncStatusIndicator style guidelines
  src/AsyncStatusIndicator/README.md
Labels: in review

#1191 Modal UX/UI guidelines - Typography fixes
  src/Modal/README.md
Labels: waiting for merge

#1192 Dropdown UX/UI guidelines - Typography fixes
  src/Dropdown/README.md
Labels: waiting for merge

#1189 More or Less UX/UI guidelines - Typography fixes
  src/MoreOrLess/README.md
Labels: waiting for merge

#1188 Meter UX/UI guidelines - Typography fixes
  src/Meter/README.md
Labels: waiting for merge

#1187 Button UX/UI guidelines - Typography fixes
  src/Button/README.md
Labels: waiting for merge

#1190 Async status indicator UX/UI guidelines - Typography fixes
  src/AsyncStatusIndicator/README.md
Labels: waiting for merge

#1193 Add Async Status indicator cover image
  src/AsyncStatusIndicator/README.md
Labels: waiting for merge

#1195 Update ResizeSensor.ts
  src/ResizeSensor/ResizeSensor.ts
Labels: waiting for merge

#1196 Update ScrollView.tsx
  src/ScrollView/ScrollView.tsx
Labels: in review

#1194 Update README.md
  src/FocusableView/README.md
Labels: WIP, in review

#1198 move BackgroundDimmer inside Modal, do not re-export it (closes #1199)
  src/BackgroundDimmer/Examples.md
  src/BackgroundDimmer/README.md
  src/BackgroundDimmer/examples.scss
  src/BackgroundDimmer/index.ts
  src/Modal/BackgroundDimmer.tsx
  src/Modal/Modal.tsx
  src/index.ts
  styleguide/setup.ts
  test/components/BackgroundDimmer.test.tsx
  test/scripts/__snapshots__/build.test.ts.snap
  test/scripts/build.test.ts
Labels: breaking, in review

#1197 Update TextOverflow README.md
  src/TextOverflow/README.md
Labels: waiting for merge

#1201 Delete README.md
  src/Divider/README.md
  src/Panel/examples.scss
Labels: in review

#1204 Add more variables to button scss
  src/Button/button.scss
Labels: waiting for merge

#1202 kill CollapsibleSection (closes #1203)
  src/CollapsibleSection/CollapsibleSection.tsx
  src/CollapsibleSection/Examples.md
  src/CollapsibleSection/README.md
  src/CollapsibleSection/collapsibleSection.scss
  src/CollapsibleSection/examples.scss
  src/CollapsibleSection/index.ts
  src/index.ts
  styleguide/setup.ts
  test/components/CollapsibleSection.test.tsx
  test/components/__snapshots__/CollapsibleSection.test.tsx.snap
  test/scripts/__snapshots__/build.test.ts.snap
Labels: breaking, waiting for merge

#1200 Update FormattedText README.md
  src/FormattedText/README.md
Labels: in review

#1206 Improve ConfirmationInput sass variables api (closes #1205)
  src/ConfirmationInput/Examples.md
  src/ConfirmationInput/confirmationInput.scss
Labels: breaking, waiting for merge

#1210 #1207: Add a basic Input component (closes #1207)
  src/ConfirmationInput/ConfirmationInput.tsx
  src/ConfirmationInput/confirmationInput.scss
  src/Input/Examples.md
  src/Input/Input.tsx
  src/Input/README.md
  src/Input/index.ts
  src/Input/input.scss
  src/index.ts
  styleguide/setup.ts
  test/scripts/__snapshots__/build.test.ts.snap
Labels: breaking

#1209 #1208: improve Dropdown sass variables (closes #1208)
  src/Dropdown/dropdown.scss
Labels: waiting for merge
