Repository buildo/react-components, pull requests merged in 2018-02, with the labels that each got.

#1180 #1179: FormattedText: there is no way to disable linkify feature (closes #1179)
  src/FormattedText/Examples.md
  src/FormattedText/FormattedText.tsx
Labels: breaking, defect, waiting for merge

#1181 #1178: FormattedText detects some words as urls incorectly (closes #1178)
  src/FormattedText/FormattedText.tsx
Labels: bug, waiting for merge

#1177 Update Modal UX/UI Guidelines
  src/Modal/README.md
Labels: waiting for merge

#1182 more-or-less-ux
  src/MoreOrLess/README.md
Labels: waiting for merge

#1184 Translating Button README
  src/Button/README.md
Labels: in review
