Repository buildo/react-components, pull requests merged in 2019-02, with the labels that each got.

#1312 Adding preview to CI
  .gitignore
  ci/pipelines/test.yml
  ci/tasks/build-preview.sh
  ci/tasks/build-preview.yml
  ci/tasks/upload-preview.sh
  ci/tasks/upload-preview.yml
  package.json
Labels: waiting for merge

#1303 #1285: Upgrade react-select to 2.x (closes #1285)
  package.json
  src/Dropdown/Dropdown.tsx
  src/Dropdown/Examples.md
  src/Dropdown/dropdown.scss
  src/Dropdown/examples.scss
  src/Dropdown/index.ts
  src/FormField/DropdownField.tsx
  src/FormField/Examples.md
  src/TextOverflow/Examples.md
  src/TimePicker/TimePicker.tsx
  test/components/Dropdown.test.tsx
  test/components/TimePicker.test.tsx
  test/components/__snapshots__/Dropdown.test.tsx.snap
  test/components/__snapshots__/TimePicker.test.tsx.snap
  yarn.lock
Labels: breaking, in review

#1316 #1315: Fix export of Dropdown.Props (closes #1315)
  src/Dropdown/Dropdown.tsx
  src/FormField/DropdownField.tsx
Labels: bug

#1317 #1313: stateless+attachToBody props make Popover crash on open (closes #1313)
  src/Popover/Popover.tsx
Labels: WIP, bug

#1319 #1314: Fix security vulnerabilities (closes #1314)
  package.json
  prettierrc.yml
  src/Panel/PanelHeader.tsx
  src/Tablo/Column/columnUtility.ts
  yarn.lock
Labels: WIP
