Repository buildo/react-components, pull requests merged in 2019-09, with the labels that each got.

#1370 Activate Mergify on PRs
  .mergify.yaml
Labels: WIP

#1374 #1373: avoid using React.ReactNode in prop typings (closes #1373)
  package.json
  src/Badge/Badge.tsx
  src/FocusableView/FocusableView.tsx
  src/Form/Form.tsx
  src/Input/Input.tsx
  src/NavBar/NavBar.tsx
  src/Panel/Panel.tsx
  src/Panel/PanelHeader.tsx
  src/Popover/Popover.tsx
  src/Scroll/ScrollView.tsx
  src/Tablo/Cell/Cell.tsx
  src/Tablo/Footer/Footer.tsx
  src/Tablo/Header/Header.tsx
  src/Tablo/plugins/columnsReorder/DNDHeader.tsx
  src/Tablo/plugins/sortable/SortableHeader.tsx
  src/TextOverflow/TextOverflow.tsx
  src/Toaster/Toaster.tsx
  src/Tooltip/Tooltip.tsx
  src/utils/index.ts
  test/components/__snapshots__/BackgroundDimmer.test.tsx.snap
  test/components/__snapshots__/Badge.test.tsx.snap
  test/components/__snapshots__/Meter.test.tsx.snap
  test/components/__snapshots__/MoreOrLess.test.tsx.snap
  yarn.lock
Labels: FE maint, breaking, in review

#1379 #1378: typings regression on TextOverflow children/label props (closes #1378)
  src/TextOverflow/TextOverflow.tsx
Labels: FE maint, in review
