Repository buildo/react-components, pull requests merged in 2019-01, with the labels that each got.

#1289 #1288: "focus" handling for Checkbox and Toggle (closes #1288)
  src/Checkbox/Checkbox.tsx
  src/Checkbox/checkbox.scss
  src/FormField/CheckboxField.tsx
  src/FormField/Examples.md
  src/FormField/FormField.tsx
  src/FormField/ToggleField.tsx
  src/Toggle/Toggle.tsx
  src/Toggle/toggle.scss
  test/components/__snapshots__/Toggle.test.tsx.snap
Labels: breaking, in review

#1291 #1290: Checkbox and Toggle are missing tcomb props for onFocus, onBlur (closes #1290)
  src/Checkbox/Checkbox.tsx
  src/Toggle/Toggle.tsx
Labels: bug, in review

#1296 switch_ci_from_drone
  .drone.yml
  ci/pipeline.yml
Labels: waiting for merge

#1302 #1294: Can't pass a React Element as label for InputField (closes #1294)
  src/FormField/InputField.tsx
  src/FormField/PasswordInputField.tsx
  src/FormField/TextareaField.tsx
Labels: bug, waiting for merge

#1299 #1298: Continuous deploy after updates on component repos (closes #1298)
  ci/pipelines/deploy.yml
  ci/pipelines/test.yml
  ci/tasks/build_showroom.sh
  ci/tasks/build_showroom.yml
  ci/tasks/test.sh
  ci/tasks/test.yml
Labels: in review

#1305 #1304: FormField style is broken (always rendered as horizontal) (closes #1304)
  src/FormField/FormField.tsx
Labels: waiting for merge

#1307 #1306: Horizontal FormField should not set flex-direction: row-reverse (closes #1306)
  src/FormField/formField.scss
Labels: waiting for merge

#1309 #1308: [FormField] Fix existing sass variables and add more customizable styling (closes #1308)
  src/FormField/DatePickerField.tsx
  src/FormField/DropdownField.tsx
  src/FormField/FormField.tsx
  src/FormField/InputField.tsx
  src/FormField/PasswordInputField.tsx
  src/FormField/TextareaField.tsx
  src/FormField/TimePickerField.tsx
  src/FormField/formField.scss
Labels: bug, in review

#1311 #1310: onClick is not prevented when the checkbox is disabled. (closes #1310)
  src/Checkbox/Checkbox.tsx
Labels: waiting for merge
