Repository buildo/react-components, pull requests merged in 2019-11, with the labels that each got.

#1388 #1387: Allow to disable submit on enter in Form (closes #1387)
  src/Form/Form.tsx
Labels: waiting for merge

#1391 #1390: [Showroom] Toggle example is not working (closes #1390)
  src/Toggle/Examples.md
Labels: WIP, bug

#1389 #1386: Add "empty states" component (closes #1386)
  src/EmptyPlaceholder/EmptyPlaceholder.tsx
  src/EmptyPlaceholder/Examples.md
  src/EmptyPlaceholder/README.md
  src/EmptyPlaceholder/emptyPlaceholder.scss
  src/EmptyPlaceholder/index.ts
  test/scripts/__snapshots__/build.test.ts.snap
Labels: FE maint, waiting for merge

#1393 #1393: noSubmitOnEnter in Form shall be optional (closes #1394)
  src/Form/Form.tsx
Labels: WIP, bug

#1396 #1392: [Showroom] EmptyPlaceholder example not working (closes #1392)
  src/EmptyPlaceholder/EmptyPlaceholder.tsx
Labels: bug, waiting for merge

#1398 #1397: [Tablo] Scrolling rows scrolls the underlying page too (closes #1397)
  package.json
  yarn.lock
Labels: FE maint, waiting for merge

#1399 #947: Dropdown: SelectAll in multi mode (closes #947)
  src/Dropdown/Examples.md
  src/Dropdown/MultiDropdownWithSelectAll.tsx
  src/Dropdown/commons.tsx
  src/Dropdown/index.ts
  src/index.ts
  test/scripts/__snapshots__/build.test.ts.snap
Labels: FE maint, waiting for merge

#1400 #1395: [Showroom] Form example not working (closes #1395)
  src/Form/Examples.md
  src/index.ts
Labels: FE maint, bug, in review

#1402 #1401: Fix EmptyPlaceholder example (closes #1401)
  src/EmptyPlaceholder/Examples.md
  src/index.ts
  styleguide/setup.ts
Labels: waiting for merge

#1406 #1405: React missing unique key warning in FormField (closes #1405)
  src/FormField/FormField.tsx
  src/FormattedText/FormattedText.tsx
Labels: FE maint, bug, waiting for merge

#1404 #1403: The way Form passes props down to the View causes React warnings (closes #1403)
  src/Form/Form.tsx
Labels: FE maint, bug, waiting for merge

#1408 #1407: Fix return type for TextOverflow's render method (closes #1407)
  src/TextOverflow/TextOverflow.tsx
Labels: waiting for merge
