Repository buildo/react-components, pull requests merged in 2019-05, with the labels that each got.

#1345 #1344: Form with "submit on enter" behavior (closes #1344)
  src/Form/Examples.md
  src/Form/Form.tsx
Labels: in review

#1350 #1349: Form defects and refinements (closes #1349)
  src/Form/Examples.md
  src/Form/Form.tsx
Labels: bug, in review

#1333 #1321: FormField Hint (closes #1321)
  src/DatePicker/DatePicker.tsx
  src/FormField/CheckboxField.tsx
  src/FormField/DatePickerField.tsx
  src/FormField/DropdownField.tsx
  src/FormField/Examples.md
  src/FormField/FormField.tsx
  src/FormField/InputField.tsx
  src/FormField/PasswordInputField.tsx
  src/FormField/RadioGroupField.tsx
  src/FormField/TextareaField.tsx
  src/FormField/TimePickerField.tsx
  src/FormField/ToggleField.tsx
  src/FormField/formField.scss
  src/Textarea/textarea.scss
Labels: in review

#1348 #1347: Remove returnFormat prop from DatePicker (closes #1347)
  src/DatePicker/DatePicker.tsx
  src/DatePicker/Examples.md
  src/FormField/DatePickerField.tsx
Labels: breaking, in review

#1353 #1352: expose components prop in TimePicker (closes #1352)
  src/TimePicker/TimePicker.tsx
Labels: waiting for merge

#1355 fixed wrong import
  src/FormField/FormField.tsx
Labels: bug, waiting for merge
