Repository buildo/react-components, pull requests merged in 2020-03, with the labels that each got.

#1425 #1424: update react-input-children version (closes #1424)
  package.json
  yarn.lock
Labels: WIP

#1426 #1423: DatePicker should have clearable option (closes #1423)
  package.json
  src/DatePicker/DatePicker.tsx
  src/FormField/DatePickerField.tsx
  yarn.lock
Labels: FE maint, breaking, bug, in review

#1429 #1427: FormField components should have a prop packing all inner component's props instead of spreading them (closes #1427)
  src/FormField/CheckboxField.tsx
  src/FormField/DatePickerField.tsx
  src/FormField/InputField.tsx
  src/FormField/MultiDropdownField.tsx
  src/FormField/PasswordInputField.tsx
  src/FormField/RadioGroupField.tsx
  src/FormField/SingleDropdownField.tsx
  src/FormField/TextareaField.tsx
  src/FormField/TimePickerField.tsx
  src/FormField/ToggleField.tsx
Labels: breaking, in review, tech debt
