Repository buildo/react-components, pull requests merged in 2020-04, with the labels that each got.

#1437 #1432: Showroom examples for InputField is broken (closes #1432)
  src/Form/Examples.md
  src/FormField/Examples.md
Labels: FE maint, waiting for merge

#1434 Call onToggle only when the new popover state is different from the o…
  src/Popover/Popover.tsx
Labels: waiting for merge

#1431 #1430: proposal: stop pinning dependencies (closes #1430)
  ci/tasks/test.sh
  depsShouldBePinned.js
  dtslint/index.d.ts
  dtslint/ts3.5/index.tsx
  dtslint/ts3.8/index.d.ts
  dtslint/ts3.8/index.tsx
  dtslint/ts3.8/tsconfig.json
  dtslint/ts3.8/tslint.json
  package.json
  src/DatePicker/DatePicker.tsx
  src/Dropdown/Dropdown.tsx
  src/Dropdown/MultiDropdown.tsx
  src/Dropdown/MultiDropdownWithSelectAll.tsx
  src/Dropdown/commons.tsx
  src/FormattedText/FormattedText.tsx
  src/Popover/Popover.tsx
  src/Tablo/Column/Column.tsx
  src/Tablo/plugins/columnsReorder/columnsReorderGrid.tsx
  src/TimePicker/TimePicker.tsx
  test/components/__snapshots__/Dropdown.test.tsx.snap
  test/components/__snapshots__/LoadingSpinner.test.tsx.snap
  test/components/__snapshots__/TimePicker.test.tsx.snap
  yarn.lock
Labels: FE maint, in review

#1438 #1436: Add parameter to customize anchor of Menu component (closes #1436)
  src/Menu/Examples.md
  src/Menu/Menu.tsx
Labels: in review

#1443 #1442: include .md files to prettier-fix script (closes #1442)
  package.json
Labels: blocked, in review

#1444 #1441: CHANGELOG is out of date (closes #1441)
  .smooth-releaserc
  CHANGELOG.md
  package.json
Labels: FE maint, waiting for merge
